[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "aoc24"
path = "main.rs"

[[bin]]
name = "day6"
path = "6/rust/day6.rs"
[[bin]]
name = "day8"
path = "8/rust/day8.rs"
