[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "3/rust"
]

[[bin]]
name = "day3"
path = "3/rust/src/main.rs"
